import React from "react";
import { createRoot } from "react-dom/client";
import Page from "./Page.jsx";

// DTCG tokens compiled to CSS custom properties — the source of truth for theme.
// Lives in src/ alongside its JSON source; regenerated by the design server.
import "./tokens.css";
import "./styles.css";

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <Page />
  </React.StrictMode>,
);
